[package]
name = "arweave-rs"
version = "0.1.0"
authors = ["littledivy <dj.srivastava23@gmail.com>"]
edition = "2018"

[dependencies]
arweave-crypto = { path = "../crypto" }
pretend = "0.3.0"

[lib]
path = "src/lib.rs"
